USE GMPT; 


UPDATE Project SET Description = "Networks project" WHERE ProjectID = 1;
UPDATE Project SET Description = "Data Structures Search Engine" WHERE ProjectID = 2;
UPDATE Project SET Description = "Networks project" WHERE ProjectID = 3;
UPDATE Project SET Description = "Financial Accounting Project" WHERE ProjectID = 4;
UPDATE Project SET Description = "Technical Entrepenueralship" WHERE ProjectID = 5;
UPDATE Project SET Description = "Management Semester Project" WHERE ProjectID = 6;
UPDATE Project SET Description = "Data Structures Search Engine" WHERE ProjectID = 7;
UPDATE Project SET Description = "Case Study" WHERE ProjectID = 8;
UPDATE Project SET Description = "Make a website" WHERE ProjectID = 9;
UPDATE Project SET Description = "Technical Entrepenueralship" WHERE ProjectID = 10;



UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 1;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 2;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 3;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 4;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 5;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 6;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 7;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 8;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 9;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 10;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 11;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 12;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 13;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 14;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 15;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 16;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 17;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 18;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 19;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 20;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 21;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 22;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 23;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 24;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 25;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 26;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 27;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 28;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 29;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 30;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 31;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 32;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 33;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 34;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 35;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 36;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 37;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 38;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 39;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 40;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 41;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 42;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 43;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 44;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 45;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 46;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 47;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 48;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 49;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 50;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 51;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 52;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 53;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 54;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 55;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 56;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 57;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 58;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 59;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 60;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 61;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 62;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 63;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 64;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 65;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 66;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 67;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 68;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 69;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 70;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 71;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 72;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 73;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 74;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 75;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 76;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 77;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 78;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 79;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 80;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 81;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 82;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 83;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 84;
UPDATE Message SET MessageText = "I hope our teacher likes this" WHERE MessageID = 85;
UPDATE Message SET MessageText = "I'll bring some snacks!" WHERE MessageID = 86;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 87;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 88;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 89;
UPDATE Message SET MessageText = "See you all in 10." WHERE MessageID = 90;
UPDATE Message SET MessageText = "We still on?" WHERE MessageID = 91;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 92;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 93;
UPDATE Message SET MessageText = "Hey, what's up?" WHERE MessageID = 94;
UPDATE Message SET MessageText = "What did you guys talk about?" WHERE MessageID = 95;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 96;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 97;
UPDATE Message SET MessageText = "Nothing really" WHERE MessageID = 98;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 99;
UPDATE Message SET MessageText = "I have other work to do sorry" WHERE MessageID = 100;
UPDATE Message SET MessageText = "I can't make it" WHERE MessageID = 101;



UPDATE Meeting SET MeetingDescription = "Plan or Design case study", LocationName = "Caruth", MeetingDate = "2016-7-11", StartTime = "08:00:00", EndTime = "10:0" WHERE MeetingID = 3;
UPDATE Meeting SET MeetingDescription = "Plan or Design project", LocationName = "Caruth", MeetingDate = "2016-7-11", StartTime = "09:30:00", EndTime = "11:30" WHERE MeetingID = 4;
UPDATE Meeting SET MeetingDescription = "Plan or Design website", LocationName = "Innovation Gym", MeetingDate = "2016-3-28", StartTime = "12:30:00", EndTime = "13:30" WHERE MeetingID = 5;
UPDATE Meeting SET MeetingDescription = "Work on group homework", LocationName = "Innovation Gym", MeetingDate = "2016-5-18", StartTime = "16:40:00", EndTime = "17:40" WHERE MeetingID = 6;
UPDATE Meeting SET MeetingDescription = "Work on project", LocationName = "Starbucks", MeetingDate = "2016-4-14", StartTime = "18:15:00", EndTime = "20:15" WHERE MeetingID = 7;
UPDATE Meeting SET MeetingDescription = "Start paper", LocationName = "Starbucks", MeetingDate = "2016-7-11", StartTime = "21:05:00", EndTime = "22:5" WHERE MeetingID = 8;
UPDATE Meeting SET MeetingDescription = "Start interview", LocationName = "Starbucks", MeetingDate = "2016-3-14", StartTime = "08:00:00", EndTime = "10:0" WHERE MeetingID = 9;
UPDATE Meeting SET MeetingDescription = "Plan or Design app", LocationName = "Fondren Library", MeetingDate = "2016-4-11", StartTime = "14:20:00", EndTime = "15:20" WHERE MeetingID = 10;
UPDATE Meeting SET MeetingDescription = "Plan or Design case study", LocationName = "Junkins", MeetingDate = "2016-4-11", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 11;
UPDATE Meeting SET MeetingDescription = "Plan or Design group homework", LocationName = "Innovation Gym", MeetingDate = "2016-5-12", StartTime = "16:40:00", EndTime = "18:40" WHERE MeetingID = 12;
UPDATE Meeting SET MeetingDescription = "Plan or Design presentation", LocationName = "Innovation Gym", MeetingDate = "2016-3-14", StartTime = "09:30:00", EndTime = "10:30" WHERE MeetingID = 13;
UPDATE Meeting SET MeetingDescription = "Work on group homework", LocationName = "Fondren Library", MeetingDate = "2016-4-14", StartTime = "16:40:00", EndTime = "17:40" WHERE MeetingID = 14;
UPDATE Meeting SET MeetingDescription = "Finish paper", LocationName = "Junkins", MeetingDate = "2016-3-28", StartTime = "22:00:00", EndTime = "0:0" WHERE MeetingID = 15;
UPDATE Meeting SET MeetingDescription = "Work on interview", LocationName = "Caruth", MeetingDate = "2016-5-18", StartTime = "08:00:00", EndTime = "9:0" WHERE MeetingID = 16;
UPDATE Meeting SET MeetingDescription = "Finish group homework", LocationName = "Starbucks", MeetingDate = "2016-3-28", StartTime = "18:15:00", EndTime = "19:15" WHERE MeetingID = 17;
UPDATE Meeting SET MeetingDescription = "Start website", LocationName = "Fondren Library", MeetingDate = "2016-7-11", StartTime = "12:30:00", EndTime = "13:30" WHERE MeetingID = 18;
UPDATE Meeting SET MeetingDescription = "Start app", LocationName = "Innovation Gym", MeetingDate = "2016-4-28", StartTime = "09:30:00", EndTime = "11:30" WHERE MeetingID = 19;
UPDATE Meeting SET MeetingDescription = "Plan or Design website", LocationName = "Starbucks", MeetingDate = "2016-5-12", StartTime = "09:30:00", EndTime = "11:30" WHERE MeetingID = 20;
UPDATE Meeting SET MeetingDescription = "Finish case study", LocationName = "Junkins", MeetingDate = "2016-7-11", StartTime = "18:15:00", EndTime = "19:15" WHERE MeetingID = 21;
UPDATE Meeting SET MeetingDescription = "Finish paper", LocationName = "Caruth", MeetingDate = "2016-7-11", StartTime = "16:40:00", EndTime = "17:40" WHERE MeetingID = 22;
UPDATE Meeting SET MeetingDescription = "Work on website", LocationName = "Caruth", MeetingDate = "2016-5-18", StartTime = "22:00:00", EndTime = "23:0" WHERE MeetingID = 23;
UPDATE Meeting SET MeetingDescription = "Start website", LocationName = "Innovation Gym", MeetingDate = "2016-4-28", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 24;
UPDATE Meeting SET MeetingDescription = "Finish app", LocationName = "Innovation Gym", MeetingDate = "2016-5-12", StartTime = "21:05:00", EndTime = "22:5" WHERE MeetingID = 25;
UPDATE Meeting SET MeetingDescription = "Plan or Design group homework", LocationName = "Innovation Gym", MeetingDate = "2016-3-28", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 26;
UPDATE Meeting SET MeetingDescription = "Finish website", LocationName = "Innovation Gym", MeetingDate = "2016-4-11", StartTime = "14:20:00", EndTime = "15:20" WHERE MeetingID = 27;
UPDATE Meeting SET MeetingDescription = "Work on presentation", LocationName = "Caruth", MeetingDate = "2016-5-18", StartTime = "14:20:00", EndTime = "16:20" WHERE MeetingID = 28;
UPDATE Meeting SET MeetingDescription = "Plan or Design interview", LocationName = "Fondren Library", MeetingDate = "2016-4-28", StartTime = "14:20:00", EndTime = "16:20" WHERE MeetingID = 29;
UPDATE Meeting SET MeetingDescription = "Plan or Design paper", LocationName = "Innovation Gym", MeetingDate = "2016-4-28", StartTime = "22:00:00", EndTime = "0:0" WHERE MeetingID = 30;
UPDATE Meeting SET MeetingDescription = "Plan or Design case study", LocationName = "Starbucks", MeetingDate = "2016-3-14", StartTime = "21:05:00", EndTime = "22:5" WHERE MeetingID = 31;
UPDATE Meeting SET MeetingDescription = "Plan or Design paper", LocationName = "Fondren Library", MeetingDate = "2016-3-28", StartTime = "22:00:00", EndTime = "0:0" WHERE MeetingID = 32;
UPDATE Meeting SET MeetingDescription = "Finish paper", LocationName = "Fondren Library", MeetingDate = "2016-7-11", StartTime = "16:40:00", EndTime = "17:40" WHERE MeetingID = 33;
UPDATE Meeting SET MeetingDescription = "Finish app", LocationName = "Innovation Gym", MeetingDate = "2016-7-11", StartTime = "21:05:00", EndTime = "22:5" WHERE MeetingID = 34;
UPDATE Meeting SET MeetingDescription = "Start project", LocationName = "Caruth", MeetingDate = "2016-5-18", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 35;
UPDATE Meeting SET MeetingDescription = "Plan or Design interview", LocationName = "Innovation Gym", MeetingDate = "2016-3-28", StartTime = "14:20:00", EndTime = "15:20" WHERE MeetingID = 36;
UPDATE Meeting SET MeetingDescription = "Finish interview", LocationName = "Starbucks", MeetingDate = "2016-4-14", StartTime = "09:30:00", EndTime = "11:30" WHERE MeetingID = 37;
UPDATE Meeting SET MeetingDescription = "Plan or Design project", LocationName = "Fondren Library", MeetingDate = "2016-5-12", StartTime = "22:00:00", EndTime = "23:0" WHERE MeetingID = 38;
UPDATE Meeting SET MeetingDescription = "Work on interview", LocationName = "Starbucks", MeetingDate = "2016-3-14", StartTime = "09:30:00", EndTime = "10:30" WHERE MeetingID = 39;
UPDATE Meeting SET MeetingDescription = "Finish app", LocationName = "Fondren Library", MeetingDate = "2016-4-28", StartTime = "22:00:00", EndTime = "0:0" WHERE MeetingID = 40;
UPDATE Meeting SET MeetingDescription = "Plan or Design case study", LocationName = "Caruth", MeetingDate = "2016-7-11", StartTime = "21:05:00", EndTime = "23:5" WHERE MeetingID = 41;
UPDATE Meeting SET MeetingDescription = "Plan or Design project", LocationName = "Starbucks", MeetingDate = "2016-4-28", StartTime = "14:20:00", EndTime = "15:20" WHERE MeetingID = 42;
UPDATE Meeting SET MeetingDescription = "Finish interview", LocationName = "Starbucks", MeetingDate = "2016-3-28", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 43;
UPDATE Meeting SET MeetingDescription = "Start presentation", LocationName = "Junkins", MeetingDate = "2016-5-12", StartTime = "13:25:00", EndTime = "15:25" WHERE MeetingID = 44;
UPDATE Meeting SET MeetingDescription = "Finish case study", LocationName = "Starbucks", MeetingDate = "2016-7-11", StartTime = "16:40:00", EndTime = "17:40" WHERE MeetingID = 45;
UPDATE Meeting SET MeetingDescription = "Finish case study", LocationName = "Fondren Library", MeetingDate = "2016-5-12", StartTime = "16:40:00", EndTime = "17:40" WHERE MeetingID = 46;
UPDATE Meeting SET MeetingDescription = "Start website", LocationName = "Starbucks", MeetingDate = "2016-4-11", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 47;
UPDATE Meeting SET MeetingDescription = "Finish website", LocationName = "Starbucks", MeetingDate = "2016-4-14", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 48;
UPDATE Meeting SET MeetingDescription = "Work on website", LocationName = "Fondren Library", MeetingDate = "2016-5-18", StartTime = "09:30:00", EndTime = "11:30" WHERE MeetingID = 49;
UPDATE Meeting SET MeetingDescription = "Plan or Design group homework", LocationName = "Caruth", MeetingDate = "2016-5-12", StartTime = "12:30:00", EndTime = "13:30" WHERE MeetingID = 50;
UPDATE Meeting SET MeetingDescription = "Work on presentation", LocationName = "Junkins", MeetingDate = "2016-4-28", StartTime = "12:30:00", EndTime = "14:30" WHERE MeetingID = 51;
UPDATE Meeting SET MeetingDescription = "Finish case study", LocationName = "Innovation Gym", MeetingDate = "2016-3-28", StartTime = "22:00:00", EndTime = "23:0" WHERE MeetingID = 52;
UPDATE Meeting SET MeetingDescription = "Work on interview", LocationName = "Fondren Library", MeetingDate = "2016-3-14", StartTime = "18:15:00", EndTime = "20:15" WHERE MeetingID = 53;
UPDATE Meeting SET MeetingDescription = "Finish presentation", LocationName = "Innovation Gym", MeetingDate = "2016-4-14", StartTime = "21:05:00", EndTime = "23:5" WHERE MeetingID = 54;



